pipeline {
  agent {
    kubernetes {
      label 'jenkins-agent-flask-app'
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: ci
spec:
  containers:
    - name: python
      image: python:3.11-slim
      command:
        - cat
      tty: true
    - name: docker
      image: docker:24-cli
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
    - name: kubectl
      image: bitnami/kubectl:1.29
      command:
        - cat
      tty: true
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
"""
    }
  }

  triggers {
    pollSCM('* * * * *')
  }

  stages {
    stage('Test python') {
      steps {
        container('python') {
          sh 'pip install --no-cache-dir -r requirements.txt'
          sh 'python test.py -v'
        }
      }
    }

    stage('Build image') {
      steps {
        container('docker') {
          sh 'docker build -t localhost:4000/pythontest:latest .'
          sh 'docker push localhost:4000/pythontest:latest'
        }
      }
    }

    stage('Deploy') {
      steps {
        container('kubectl') {
          sh 'kubectl apply -f ./kubernetes/deployment.yaml'
          sh 'kubectl apply -f ./kubernetes/service.yaml'
        }
      }
    }
  }
}
